spring:
  application:
    name: payment-service
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
    discovery:
      enabled: false
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          okta:
            token-uri: https://dev-78958050.okta.com/oauth2/default/v1/token
        registration:
          okta:
            authorization-grant-type: client_credentials
            client-id: ${OKTA_API_SERVICES_ID}
            client-secret: ${OKTA_API_SERVICES_SECRET}
            scope: stripe_client
eureka:
  client:
    enabled: false
#okta:
#  oauth2:
#    issuer: ${OKTA_ISSUER}
#    client-secret: ${OKTA_CLIENT_SECRET}
#    client-id: ${OKTA_CLIENT_ID}
STRIPE_SECRET_KEY: ${STRIPE_TEST_SECRET_KEY}
