spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost/realms/test/protocol/openid-connect/certs
  application:
    name: message-service
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
    discovery:
      enabled: false
    config:
      enabled: false
  mongodb:
    embedded:
      version: 4.4.16
  data:
    mongodb:
      port: 27018
eureka:
  client:
    enabled: false
